apiVersion: apps/v1
kind: Deployment
metadata:
  name: une-ai-sso
  namespace: #{namespace}#  
  annotations:
    azure-devops/commit-id: "#{Build.SourceVersion}#"
    azure-devops/build-id: "#{Build.BuildId}#"
    azure-devops/pipeline-name: "#{Build.DefinitionName}#"
    azure-devops/build-date: "#{Build.BuildNumber}#"
spec: 
  replicas: #{minReplicas}#
  selector:
    matchLabels:
      app: une-ai-sso
  template:
    metadata:
      labels:
        app: une-ai-sso
    spec:
      containers:
      - name: une-ai-sso
        image: acrunebrs01.azurecr.io/une-ai-sso-#{env}#:#{env}#-#{Build.BuildId}#
        ports:
        - name: web
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "#{memoryRequest}#"
            cpu: "#{cpuRequest}#"
          limits:
            memory: "#{memoryLimit}#"
            cpu: "#{cpuLimit}#"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3